USE [master]
GO

/****** Object:  Database [WebStore]    Script Date: 8/4/2017 12:49:35 PM ******/
CREATE DATABASE [WebStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\WebStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\WebStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [WebStore] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebStore] SET RECOVERY FULL 
GO

ALTER DATABASE [WebStore] SET  MULTI_USER 
GO

ALTER DATABASE [WebStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebStore] SET QUERY_STORE = OFF
GO

USE [WebStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [WebStore] SET  READ_WRITE 
GO


